# Порт для сокет-сервера
socket:
  port: 60777

# Разрешенные IP-адреса
allowed_ips:
  - "185.197.33.12"
  - "194.87.209.184"

# Радиус по умолчанию для слышимости
radius: 50.0

# Название сервера (используется в ссылках)
name: "myserver"

# Права доступа к командам
commands:
  reload:
    default_access: false
  link:
    default_access: true
  code:
    default_access: true
  off:
    default_access: true
  on:
    default_access: true
  mute:
    default_access: true
  unmute:
    default_access: true
  listen:
    default_access: false
  myradius:
    default_access: false